#! /bin/sh
#
# switchoff	Open shell at shutdown
#
# chkconfig: S 6 0
#

PATH=/lib/init:/bin:/sbin:/usr/bin:/usr/sbin

REBOOT=`cat /var/config/shutdown/reboot`
if [ "$REBOOT" = "reboot" ]; then
	# keine schleife Reboot ...
	init 6
else
	/bin/echo "Herunterfahren" > /dev/vfd
fi

sleep 3

# wenn kein VIP2 FB starten
DEEPSTANDBY=`cat /proc/Boxtype`

if [ "$DEEPSTANDBY" = "Vip2" ]; then
	sync
	sleep 1
	fp_control -d
elif [ "$DEEPSTANDBY" = "Vip1v2" ]; then
	sync
	sleep 1
	fp_control -d
else
	# Aktiviere Display Uhr anzeige für Box OFF
	/var/config/time.sh &

	# Disable HDMI
	fp_control -d

	echo "remount /ram as rw"
	mount -t ramfs ramfs /ram -o size=65%

	# nandcheck, ist keys ausgelagert muss nand gemounted sein
	nandcheck=`cat /var/config/nanduse`
	if [ "$nandcheck" = "jffs2-nand-e2" ]; then
		echo "Nand Speicher mounten für E2..."
		mount -t jffs2 /dev/mtdblock1 /media/nand
	fi 

	#start remote control for Vip1 & Opti for wake up
	/usr/bin/lircd -P /ram/lircd.pid -o /ram/lircd

	fb=`cat /var/keys/Benutzerdaten/.system/fernbedienung`
	if [ "$fb" = "neu" ]; then
		/bin/evremote2 -x vip2 &
	elif [ "$fb" = "alt" ]; then
		/bin/evremote2 -x vip1 &
	elif [ "$fb" = "opti" ]; then
		/bin/evremote2 -x opti &
	elif [ "$fb" = "Pungolux" ]; then
		/bin/evremote2 -x Pingolux &
	fi
	# Set HDD Spindown
	if [ `fdisk -l | grep -c "/dev/sdb1" | awk '{ print $1 }'` = 1 ]; then
		sdparm --command=stop /dev/sdb
	fi

	rm /ram/autoswitch.tmp

	sleep 1

	# start the loop

	until false
	do
	file="/ram/autoswitch.tmp"
	if [ -e $file ]; then
		echo "Neustart" > /dev/vfd
		swapoff /dev/sda3
		sync
		sleep 2
		init 6
		exit 1
	else 	
		sleep 3
	fi 
	done
fi

