ifdef STM23
obj-y	+= rt2870sta/
obj-y	+= rt3070sta/
obj-y	+= rt5370sta/
obj-y	+= rtl8192cu_hs7110/
obj-y	+= rtl871x/
obj-y	+= rpi-rtl8188eu-master/
else
obj-y	+= rt2870sta/
obj-y	+= rt3070sta/
obj-y	+= rt5370sta/
obj-y	+= rtl8192cu/
obj-y	+= rpi-rtl8188eu-master/
endif
